const loader=document.querySelector('.loader');window.addEventListener('load',()=>setTimeout(()=>loader?.classList.add('hide'),420));
document.addEventListener('mousemove',e=>{document.documentElement.style.setProperty('--mx',e.clientX+'px');document.documentElement.style.setProperty('--my',e.clientY+'px')});
const menu=document.querySelector('.menu'),mobile=document.querySelector('.mobile');menu?.addEventListener('click',()=>{mobile.classList.toggle('open');menu.setAttribute('aria-expanded',mobile.classList.contains('open'))});mobile?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobile.classList.remove('open')));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach((e,i)=>{e.style.setProperty('--i',i);io.observe(e)});
const current=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('[data-page]').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===current));
function emailValid(v){return /^[a-z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$/.test(v)&&v===v.toLowerCase()&&v.includes('.')}
function setupForm(form){if(!form)return;const err=form.querySelector('.form-error'),success=form.querySelector('.success'),btn=form.querySelector('[type=submit]');form.addEventListener('submit',async e=>{e.preventDefault();err.classList.remove('show');success.classList.remove('show');const email=form.querySelector('[type=email]'),country=form.querySelector('[name=country]'),phone=form.querySelector('[name=phone]');if(email&&!emailValid(email.value.trim())){err.textContent='Please enter a valid lowercase email address, for example name@gmail.com.';err.classList.add('show');email.focus();return}if(phone&&country){const digits=phone.value.replace(/\D/g,'');const code=country.value;if(!code){err.textContent='Please select your country first.';err.classList.add('show');return}if(digits.length<7||digits.length>15){err.textContent='Please enter a valid phone number (7–15 digits).';err.classList.add('show');phone.focus();return}}const original=btn.innerHTML;btn.disabled=true;btn.innerHTML='Sending…';try{const fd=new FormData(form);const r=await fetch(form.action,{method:'POST',body:fd,headers:{Accept:'application/json'}});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.message||'Submission failed');form.reset();success.classList.add('show');success.scrollIntoView({behavior:'smooth',block:'center'})}catch(x){err.textContent='We could not send the form right now. Please check your connection and try again.';err.classList.add('show')}finally{btn.disabled=false;btn.innerHTML=original}});
countryMask(form)}
function countryMask(form){const c=form.querySelector('[name=country]'),p=form.querySelector('[name=phone]');if(!c||!p)return;c.addEventListener('change',()=>{p.placeholder=c.selectedOptions[0]?.dataset.example||'Phone number';p.value=p.value.replace(/\D/g,'')});p.addEventListener('input',()=>{p.value=p.value.replace(/[^0-9\s().-]/g,'')})}
document.querySelectorAll('form[data-ovia]').forEach(setupForm);
